require("__planet-machina__.prototypes.planet.routes")
require("__planet-machina__.prototypes.planet.shipyard.shipyard_planet")
require("__planet-machina__.prototypes.planet.shipyard.shipyard_tiles")
-- require("__planet-machina__.prototypes.planet.ostendus.ostendus_planet")
-- require("__planet-machina__.prototypes.planet.ostendus.ostendus_tiles")
require("__planet-machina__.prototypes.planet.nix.nix_planet")
require("__planet-machina__.prototypes.planet.nix.nix_tiles")
require("__planet-machina__.prototypes.planet.ringworld.ringworld_planet")
require("__planet-machina__.prototypes.planet.ringworld.ringworld_tiles")
require("__planet-machina__.prototypes.planet.ringworld.ringworld_resource_expressions")
-- require("__planet-machina__.prototypes.planet.caelum.caelum_planet")
-- require("__planet-machina__.prototypes.planet.caelum.caelum_tiles")
require("__planet-machina__.prototypes.planet.ostendus.mirandus_system")
-- require("__planet-machina__.prototypes.planet.luxaqua.luxaqua_planet")
-- require("__planet-machina__.prototypes.planet.luxaqua.luxaqua_tiles")
require("__planet-machina__.prototypes.planet.technology")
require("__planet-machina__.prototypes.fluid")
require("__planet-machina__.prototypes.item.item")
require("__planet-machina__.prototypes.item.metals")
require("__planet-machina__.prototypes.entity.particle-accelerator")
require("__planet-machina__.prototypes.entity.gravity-assembler")
require("__planet-machina__.prototypes.entity.chemical-stager")
require("__planet-machina__.prototypes.entity.resources")
require("__planet-machina__.prototypes.entity.quantum-stabilizer")
require("__planet-machina__.prototypes.entity.conduit")
require("__planet-machina__.prototypes.movethis")
require("__planet-machina__.prototypes.recipe-category")
require("__planet-machina__.prototypes.recipe")
require("__planet-machina__.prototypes.recycling")
require("__planet-machina__.prototypes.conversion-recipes")
require("__planet-machina__.prototypes.ammos")
require("__planet-machina__.prototypes.entity.accumulators")
require("__planet-machina__.prototypes.autoplace-controls")
require("__planet-machina__.prototypes.units")
require("__planet-machina__.prototypes.entity.asteroids.asteroid")
require("__planet-machina__.prototypes.entity.asteroids.smoke")
require("__planet-machina__.prototypes.entity.asteroids.explosions")
require("__planet-machina__.prototypes.entity.asteroids.particles")
require("__planet-machina__.prototypes.entity.asteroids.particle-animations")
require("__planet-machina__.prototypes.entity.asteroids.factoriopedia-simulations")

