data:extend(
{
  {
    type = "fluid",
    name = "gray-goo",
    icon = "__planet-machina__/graphics/icons/gray-goo.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[grey-goo]",
    default_temperature = -50,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "mirandite-sludge",
    icon = "__planet-machina__/graphics/icons/mirandite-sludge.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[mirandite-sludge]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "dark-matter-fluid",
    icon = "__planet-machina__/graphics/icons/dark-matter-gas.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[dark-matter-fluid]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0.15, 0, 0.4},
    flow_color = {0.35, 0, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "helium",
    icon = "__planet-machina__/graphics/icons/helium.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[helium]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "crude-slush",
    icon = "__planet-machina__/graphics/icons/crude-slush.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[crude-slush]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "heavy-water",
    icon = "__planet-machina__/graphics/icons/heavy-water.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[heavy-water]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-gold",
    icon = "__planet-machina__/graphics/icons/molten-gold.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[heavy-water]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-glass",
    icon = "__planet-machina__/graphics/icons/molten-glass.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[shipyard]-a[heavy-water]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  --/////refined liquid fuels
  {
    type = "fluid",
    name = "liquid-rocket-fuel",
    icon = "__planet-machina__/graphics/icons/molten-glass.png",
    subgroup = "fluid",
    order = "a[fluid]-b[refined-fuel]-c[rocket-fuel]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    fuel_value = "11MJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "liquid-nuclear-fuel",
    icon = "__planet-machina__/graphics/icons/molten-glass.png",
    subgroup = "fluid",
    order = "a[fluid]-b[refined-fuel]-c[nuclear-fuel]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    fuel_value = "133MJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "liquid-dark-matter-fuel",
    icon = "__planet-machina__/graphics/icons/molten-glass.png",
    subgroup = "fluid",
    order = "a[fluid]-b[refined-fuel]-c[dark-matter-fuel]",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    fuel_value = "72MJ",
    base_color = {0.2, 0.2, 0.25},
    flow_color = {0.7, 0.7, 0.75},
    auto_barrel = false
  },
})